[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; --- Hardware Performance Optimizations ---
board_build.f_cpu = 240000000L    
board_build.f_flash = 80000000L   
board_build.flash_mode = qio      

; --- Filesystem and Partitions ---
board_build.filesystem = littlefs
board_build.partitions = no_ota.csv 

; --- Library Dependencies ---
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    bblanchon/ArduinoJson @ ^7.4.3
    hideakitai/ESP32SPISlave @ ^0.3.0